version: '3'

services:
  container1:
    image: harjot33/dockerhub:container1
    ports:
      - "5000:5000"
    links:
      - container2
    networks:
      - backend
  container2:
      image: harjot33/dockerhub:container2
      ports:
        - "5001:5001"
      volumes:
        - $PWD/:/vol
      networks:
        - backend
networks:
  backend:
    driver: "bridge"


